title: LitElement Documentation
toc:
  try: 
    # title: Try LitElement
    # desc: Try LitElement with interactive code samples.
    title: 試してみる
    desc: サンプルをオンラインエディタで試してみる
    url: /guide/try
  introduction: 
    # title: Introduction
    title: はじめに
    url: /guide
  templates: 
    # title: Templates
    # desc: Create and render LitElement templates. Use JavaScript expressions to add properties and logic.
    title: テンプレート
    desc: テンプレートを作り、描画する。JavaScript式でプロパティとロジックを追加する
    url: /guide/templates
  styles:
    # title: CSS Styles
    # desc: Style your elements with CSS.
    title: スタイリング
    desc: CSSでスタイリング
    url: /guide/styles
  properties: 
    # title: Properties
    # desc: Declare and configure a component's properties and attributes.
    title: プロパティ
    desc: プロパティや属性を定義、設定する
    url: /guide/properties
  lifecycle: 
    # title: Lifecycle
    # desc: Specify when an element should update. Respond to updates, or wait for an update to complete.
    title: ライフサイクル
    desc: 描画すべきタイミング、更新やその処理を待つタイミングを指定する
    url: /guide/lifecycle
  tools:
    # title: Tools
    # desc: Tools for developing and deploying LitElement projects.
    title: ツール
    desc: 開発ツールと構築方法
    url: /guide/tools
