name: LitElement
description: 軽量で高速なWebコンポーネントをつくるシンプルなベースクラス
exclude: [package.json, polymer.json, src, node_modules, package-lock.json]
markdown: kramdown
kramdown:
  parse_block_html: true
google_analytics: UA-131004707-2
projects: includes/projects
collections:
  includes:
    output: true
  guide:
    output: true
include:
  - "_*_.html"
  - "_*_.*.html"
