steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: docs
  args: ['install']
- name: 'gcr.io/$PROJECT_ID/polymer'
  dir: docs
  args: ['build']
- name: 'ubuntu'
  args: ['mkdir', '-p', 'docs/_site']
- name: jekyll/jekyll
  dir: docs
  args: ['jekyll', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  dir: docs
  args: ['app', 'deploy', '_site/app.yaml', '--project', 'polymer-japan']
